### ISSUE TITLE
这。。。

### ISSUE THREAD

**Issue by apporoad** [yyrdl/cc#1]
try {

		module.exports = cc;

	} catch (e) {}

	try {

		window.cc = cc;

	} catch (e) {}

只是吐槽下，这个。。。。

**Comment by yyrdl** [comment]
这个库纯粹写着玩的，一般前端都采用async/await 然后babel 转译吧

**Comment by apporoad** [comment]
我这有这样的场景，需要兼容ES5，然后又需要没有依赖的，快速集成到项目里去，所以找到了你这个项目，不过你的接口感觉有点太难用了，支持promise就好了

**Comment by yyrdl** [comment]
这个项目还可以进化一下， 没时间去弄。  async/await 写出来babel转译成es5的语法也行啊，只是在开发阶段有依赖，release 的是转译之后的代码，不会有依赖的

**Comment by yyrdl** [comment]
你可以给一段你的代码，我用 cc 给你重写，应该是蛮容易的

**Comment by yyrdl** [comment]
支持Promise 了， readme 里面有写demo  。  不做任何转译，想要在es5的语言基础上 直接将异步的逻辑写成同步的代码，感觉就只能做成这个样子了。 babel 能让你用比es5 更新的语法 写同步形式的代码，但他需要转译成es5，而且转译之后的代码形式不是同步的

**Comment by apporoad** [comment]
good job
